all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: devops-resume
    app_port: 5000
    docker_image: devops-resume:latest
