all:
  hosts:
    yandex-vm:
      ansible_host: 81.26.185.204
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/devops-resume
      ansible_python_interpreter: /usr/bin/python3
  vars:
    app_name: devops-resume
    app_port: 5001
    docker_image: devops-resume:latest
