apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-resume-ingress
  namespace: devops-resume
  labels:
    app: devops-resume
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: devops-resume.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-resume-service
            port:
              number: 80
  tls:
  - hosts:
    - devops-resume.local
    secretName: devops-resume-tls
