apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-resume-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: devops-resume.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: devops-resume-service
            port:
              number: 80
