apiVersion: v1
kind: Service
metadata:
  name: devops-resume-service
  namespace: devops-resume
  labels:
    app: devops-resume
spec:
  selector:
    app: devops-resume
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP
